examples/erp/drizzle/0001_tricky_strong_guy.sql, examples/erp/drizzle/meta/0001_snapshot.json, examples/erp/drizzle/meta/_journal.json
- missing foodAvatar in Drizzle migration
- Generate new migration
=> chore: missing foodAvatar migration

.changeset/orange-falcons-listen.md, packages/rest/src/index.ts
- To let user alter request object e.g. Adding Authorization Header from cookie or localStorage.
- Add `before` option to rest client
=> [Feature] Add "before" middleware for @genseki/rest package

.changeset/purple-buttons-bathe.md, packages/react-query/src/index.ts
=> Fix React Query wrong useMutation's options

.changeset/clean-teams-sin.md, packages/next/src/resource.ts
=> Fix NextJs resource route response

.changeset/calm-eagles-doubt.md, packages/next/src/resource.ts, packages/next/src/server-function.ts, packages/react/src/react/views/collections/create.tsx, packages/react/src/react/views/collections/list.tsx, packages/react/src/react/views/collections/one.tsx, packages/react/src/react/views/collections/update.tsx
- Authentication is not working as expect.
- Fix Context.toRequestContext
=> Fix request context misconfigure

.changeset/neat-apricots-tan.md, examples/erp/db/schema/index.ts, examples/erp/drizzle/0002_black_doctor_strange.sql, examples/erp/drizzle/0003_spicy_madame_web.sql, examples/erp/drizzle/meta/0002_snapshot.json, examples/erp/drizzle/meta/0003_snapshot.json, examples/erp/drizzle/meta/_journal.json, examples/erp/drizzlify/collections/foods.tsx, packages/react/src/react/components/compound/auto-field/client.tsx, packages/react/src/react/views/auth/sign-up.client.tsx
=> Revert "Revert "chore: create or connect in many relation""

.changeset/legal-candies-accept.md, packages/react/src/auth/handlers/sign-out.ts
=> Fix set cookie when logout

.changeset/blue-icons-search.md, packages/react/src/react/components/compound/auto-field/client.tsx, packages/react/src/react/components/compound/file-upload-field.tsx
- i want to disable field in custom preview page
- add isDisable to AutoField
=> feat: can disable in autofield

.changeset/hip-impalas-hunt.md, packages/react/src/react/components/primitives/avatar.tsx, packages/react/src/react/components/primitives/card.tsx
- because card and avatar is not client component
- 'use client'
=> fix: card and avatar is not client component

.changeset/chilled-garlics-travel.md, packages/prisma-generator/package.json, packages/prisma-generator/src/globals/index.ts, pnpm-lock.yaml
=> [Fix] Add bundle script for Prisma generator

.changeset/neat-steaks-attack.md, examples/erp/genseki/config.tsx, examples/erp/prisma/migrations/20250729093638_add_role/migration.sql, examples/erp/prisma/schema.prisma, packages/plugins/src/admin/index.ts, packages/react/src/auth/base.ts, packages/react/src/auth/plugins/email-and-password/index.tsx, packages/react/src/auth/plugins/email-and-password/service.ts, packages/react/src/core/index.ts, packages/react/src/core/table.ts
- Validate schema before let user defining options
=> [Fix] Improve Plugin type-guard

.changeset/fuzzy-kids-kneel.md, .github/workflows/ci.yaml, packages/react/src/auth/utils.ts
=> [Fix] Build error due to using node-specific module

.changeset/plenty-zoos-sort.md, packages/react/src/core/builder.tsx
- Somehow, the home page is missing.
- Fixed the collection home page registration route
=> [Fix] Missing collection home page

.changeset/gold-foxes-greet.md, packages/react/src/core/index.ts
=> feat export createGensekiUiRoute

.changeset/rich-radios-sit.md, packages/react-query/src/index.ts
=> [Fix] `useInvalidateQuery` does not match its type

.changeset/silent-candles-know.md, examples/erp/genseki/collections/posts.tsx, packages/react/src/core/config.tsx, packages/react/src/react/components/compound/auto-field/index.tsx
- Add label for Select
- Remove omit `options` in getFieldsClient since it's now safe to send to client (it's a string)
=> [Fix] getFieldsClient wrong omit field

.changeset/chubby-phones-judge.md, examples/erp/genseki/config.tsx, packages/react/src/core/config.tsx, packages/react/src/core/endpoint.ts, packages/react/src/core/file-storage-adapters/generic-adapter.ts, packages/react/src/core/file-storage-adapters/handlers/grab-get-obj-signed-url.ts, packages/react/src/core/file-storage-adapters/handlers/grab-permanent-obj.ts, packages/react/src/core/file-storage-adapters/handlers/grab-put-obj-signed-url.ts, packages/react/src/core/file-storage-adapters/index.ts, packages/react/src/core/file-storage-adapters/s3/upload-adapter.ts, packages/react/src/react/components/compound/file-upload-field.tsx, packages/react/src/react/utils/is-image-key.ts
Add S3 uploader
Add S3 uploader using `createFileUploadHandlers` from YU
Fix mimeType options gone
Please use env like this that match with variables.
```
AWS_BUCKET_NAME
AWS_REGION
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
```
=> feat: add file uploader

.changeset/chubby-phones-judge.md
Fix unavailable semantic versioning on [PR 142](https://github.com/softnetics/genseki/pull/142)
-
=> fix: unavailable semantic versioning on PR 142

.changeset/forty-fans-sniff.md, examples/erp/genseki/collections/users.ts, packages/react/src/core/config.tsx, packages/react/src/core/file-storage-adapters/generic-adapter.ts, packages/react/src/core/file-storage-adapters/handlers/grab-delete-obj-signed-url.ts, packages/react/src/core/file-storage-adapters/handlers/index.ts, packages/react/src/core/file-storage-adapters/s3/upload-adapter.ts, packages/react/src/react/components/compound/file-upload-field.tsx
-  Add delete object from storage
https://github.com/user-attachments/assets/3f5578f3-cefe-4021-8918-89addf9a6f50
=> feature: delete object from storage

.changeset/ninety-adults-invent.md, examples/erp/genseki/collections/tags.ts, packages/react/src/react/views/collections/list/context.tsx, packages/react/src/react/views/collections/list/default.tsx
- delete single item is don't work
- sent id to deleteRows
=> fix: can't delete single
